# Generated by Django 5.2 on 2025-04-08 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airliner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('exits', models.IntegerField(blank=True, null=True)),
                ('restrooms', models.IntegerField(blank=True, null=True)),
                ('crew_capacity', models.IntegerField(blank=True, help_text='not including cockpit crew', null=True)),
                ('cockpit_crew_capacity', models.IntegerField(blank=True, help_text='not including flight attendants', null=True)),
                ('range', models.DecimalField(blank=True, decimal_places=5, help_text='kilometers', max_digits=13, null=True)),
                ('max_speed', models.DecimalField(blank=True, decimal_places=5, help_text='km/h', max_digits=13, null=True)),
                ('cruising_speed', models.DecimalField(blank=True, decimal_places=5, help_text='km/h', max_digits=13, null=True)),
                ('fuel_capacity', models.DecimalField(blank=True, decimal_places=5, help_text='liters', max_digits=13, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=5, help_text='kg', max_digits=13, null=True)),
                ('weight_capacity', models.DecimalField(blank=True, decimal_places=5, help_text='kg', max_digits=13, null=True)),
                ('passenger_capacity', models.IntegerField(blank=True, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=5, help_text='meters', max_digits=13, null=True)),
                ('wingspan', models.DecimalField(blank=True, decimal_places=5, help_text='meters', max_digits=13, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=5, help_text='meters', max_digits=13, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Plane Models',
                'ordering': ['manufacturer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first_class', 'First Class')], default='economy', max_length=50)),
                ('position', models.CharField(choices=[('aisle', 'Aisle'), ('window', 'Window'), ('middle', 'Middle')], default='window', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Seat Types',
                'ordering': ['type', 'position'],
            },
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_num', models.CharField(blank=True, max_length=10, null=True)),
                ('street_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='airliner.country')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'ordering': ['street_name', 'city'],
            },
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='airliner.country')),
            ],
            options={
                'verbose_name_plural': 'Airlines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='airliner.address')),
            ],
            options={
                'verbose_name_plural': 'Airports',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='airliner.address')),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequent_flyer_number', models.CharField(blank=True, max_length=20, null=True)),
                ('loyalty_program', models.CharField(blank=True, max_length=50, null=True)),
                ('accomodations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airliner.contact')),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'ordering': ['contact__last_name', 'contact__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('confirmation_number', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airliner.customer')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
                'ordering': ['customer__contact__last_name', 'customer__contact__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(choices=[('pilot', 'Pilot'), ('flight_attendant', 'Flight Attendant'), ('ground_staff', 'Ground Staff'), ('maintenance', 'Maintenance')], default='pilot', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airliner.airline')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airliner.contact')),
            ],
            options={
                'verbose_name_plural': 'Employees',
                'ordering': ['contact__last_name', 'contact__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=8)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_flights', to='airliner.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_flights', to='airliner.airport')),
            ],
            options={
                'verbose_name_plural': 'Flights',
                'ordering': ['flight_number'],
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airliner.employee')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airliner.flight')),
            ],
            options={
                'verbose_name_plural': 'Crew',
                'ordering': ['flight', 'employee__contact__last_name', 'employee__contact__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('registration_number', models.CharField(max_length=10, unique=True)),
                ('manufacturing_year', models.IntegerField(blank=True, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airliner.airline')),
                ('airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airliner.airport')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airliner.planemodel')),
            ],
            options={
                'verbose_name_plural': 'Planes',
                'ordering': ['airline', 'model'],
            },
        ),
        migrations.AddField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airliner.plane'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('aisle', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airliner.plane')),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='airliner.seattype')),
            ],
            options={
                'verbose_name_plural': 'Seats',
                'ordering': ['plane', 'row', 'aisle'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airliner.booking')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airliner.flight')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airliner.seat')),
            ],
            options={
                'verbose_name_plural': 'Tickets',
                'ordering': ['booking__customer__contact__last_name', 'booking__customer__contact__first_name'],
            },
        ),
    ]
